
social:
- {icon: 'twitter', link: 'https://twitter.com/ThuyNguyenPhuo3'}
- {icon: 'linkedin', link: 'http://linkedin.com/in/phuong-thuy-nguyen-84718910a'}

contacts:
- {name: 'Thuy T.P. Nguyen, PhD', title: 'PhD', department: 'Animal Metabolism', institution: 'Chonnam National University', email: 'nguyenphuongthuydkh@gmail.com'}
